#!/usr/bin/python

import os,time


def main():
	x=raw_input('WARNING!!! Name node should be configured first!!\nAre you shure you want to run?\ny/n\n>')
	if x=='y':
		data_send()
	else:
		print 'name node setup is being started'
		time.sleep(3)
		os.system('./name_node_setup')
	
def data_send():			
	tmp=open('hosts.txt','r')
	v=tmp.read()
	x=v.split('\n')
	for line in x:
		os.system('sshpass -p \'redhat\' scp data_node root@'+line+':/bin/') #data node file is copied to all the systems detected by nmap
		os.system('sshpass -p \'redhat\' ssh -o StrictHostKeyChecking=no root@'+line+' data_node') #datanode configuration script will be executed
		print line+'configured!!'
	tmp.close()
	
main()
