#!/usr/bin/python
import os

def console():
	ip='<name_node_ip>'
	check=True
	while check:
		print 'Enter 1 to check running services'
		print 'Enter 2 to see the report'
		print 'Enter anything to exit'
		ck=int(raw_input('>'))
		if ck==1:
			 os.system('sshpass -p \'redhat\' ssh -o StrictHostKeyChecking=no root@'+ip+' jps')
		elif ck==2:
			os.system('sshpass -p \'redhat\' ssh -o StrictHostKeyChecking=no root@'+ip+' hadoop dfsadmin -report')
		else:
			check=False
			
console()
