#!/usr/bin/python
import os,fileinput

def main():
	snn():


def snn():
	sip=raw_input('Enter the ip of secondary namenode')#ip of secondary namenode is entered
	#ip of secondary namenode is set in secondary_name_node file   
	temp=open('secondary_name_node','r+') 
	for line in fileinput.input('secondary_name_node'):
		temp.write(line.replace("<ip_of_snn>",sip))
	temp.close()
	#ip of secondary namenode is set in name_node file
	temp=open('name_node','r+')
	for line in fileinput.input('name_node'):
		temp.write(line.replace("<ip_of_snn>",sip))
	temp.close()
	#ip of secondary namenode is removed from the hosts file in order to avoide further conflicts
	temp=open('hosts.txt','r+')
	for line in fileinput.input('hosts.txt'):
		temp.write(line.replace(sip,''))
	temp.close()
	#the secondary_name_node file is copied to the system which is going to be the secondary namenode and is executed
	os.system('sshpass -p \'redhat\' scp secondary_name_node root@'+sip+':/bin/')
	os.system('sshpass -p \'redhat\' ssh -o StrictHostKeyChecking=no root@'+sip+' secondary_name_node')
	print 'done!!'
	







main()
