#!/usr/bin/python
import os,time,fileinput

def main():
	start()

def start():
	ip='<name_node_ip>'			
	os.system('sshpass -p \'redhat\' scp start_hadoop root@'+ip+':/bin/')
	os.system('sshpass -p \'redhat\' ssh -o StrictHostKeyChecking=no root@'+ip+' start_hadoop')
	
main()
